name: ai-base
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.24.3
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - tensorflow=2.13.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - transformers=4.31.0
  - jupyter=1.0.0
  - notebook=6.5.4
  - ipykernel=6.23.2
  - fastapi=0.100.0
  - uvicorn=0.23.1
  - pydantic=1.10.9
  - sqlite=3.41.2
  - psycopg2=2.9.6
  - faiss-cpu=1.7.4
